language: python
python:
  - "3.6"

env:
  - DJANGO_SETTINGS_MODULE=tfoosball.config.dev_settings

install:
  - pip install -r requirements.txt
script:
  - flake8
  - python manage.py test

before_install:
  - export DJANGO_SETTINGS_MODULE=tfoosball.config.dev_settings
  - export PYTHONPATH=$HOME/builds/TeoTN/TFoosball-API
  - export PIP_USE_MIRRORS=true
