# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0003_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='curr_lose_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='curr_win_streak',
            field=models.IntegerField(default=0),
        ),
    ]
