# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0004_auto_20161023_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('exp', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
