# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0011_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=14)),
                ('exp', models.IntegerField(default=1000)),
                ('offence', models.IntegerField(default=0)),
                ('defence', models.IntegerField(default=0)),
                ('played', models.IntegerField(default=0)),
                ('win_streak', models.IntegerField(default=0)),
                ('curr_win_streak', models.IntegerField(default=0)),
                ('lose_streak', models.IntegerField(default=0)),
                ('curr_lose_streak', models.IntegerField(default=0)),
                ('lowest_exp', models.IntegerField(default=1000)),
                ('highest_exp', models.IntegerField(default=1000)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfoosball.Team')),
            ],
        ),
    ]
