# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0012_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='MatchLegacy',
        ),
        migrations.AlterField(
            model_name='matchlegacy',
            name='blue_att',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='blue_att', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchlegacy',
            name='blue_def',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='blue_def', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchlegacy',
            name='red_att',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='red_att',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchlegacy',
            name='red_def',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='red_def',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
