# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0012_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='MatchLegacy',
        ),
    ]
