# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0015_auto_20170207_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exphistory',
            name='match',
        ),
        migrations.RemoveField(
            model_name='exphistory',
            name='player',
        ),
        migrations.DeleteModel(
            name='ExpHistory',
        ),
    ]
