# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0015_exphistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('red_score', models.IntegerField()),
                ('blue_score', models.IntegerField()),
                ('points', models.IntegerField()),
                ('status', models.IntegerField(default=20)),
                ('blue_att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_att', to='tfoosball.Member')),
                ('blue_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_def', to='tfoosball.Member')),
                ('red_att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_att', to='tfoosball.Member')),
                ('red_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_def', to='tfoosball.Member')),
            ],
        ),
    ]
