# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0016_auto_20170207_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('exp', models.IntegerField()),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_history', to='tfoosball.MatchLegacy')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_history', to='tfoosball.Member')),
            ],
        ),
    ]
