# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 21:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0016_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exphistory',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_history', to='tfoosball.Match'),
        ),
        migrations.AlterField(
            model_name='team',
            name='domain',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]+$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
