# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0017_auto_20170207_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='is_team_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(through='tfoosball.Member', to='tfoosball.Team'),
        ),
    ]
