# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 13:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0018_auto_20170214_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='domain',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]+$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
