# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0019_auto_20170219_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exphistorylegacy',
            name='match',
        ),
        migrations.RemoveField(
            model_name='exphistorylegacy',
            name='player',
        ),
        migrations.RemoveField(
            model_name='matchlegacy',
            name='blue_att',
        ),
        migrations.RemoveField(
            model_name='matchlegacy',
            name='blue_def',
        ),
        migrations.RemoveField(
            model_name='matchlegacy',
            name='red_att',
        ),
        migrations.RemoveField(
            model_name='matchlegacy',
            name='red_def',
        ),
        migrations.RemoveField(
            model_name='player',
            name='curr_lose_streak',
        ),
        migrations.RemoveField(
            model_name='player',
            name='curr_win_streak',
        ),
        migrations.RemoveField(
            model_name='player',
            name='defence',
        ),
        migrations.RemoveField(
            model_name='player',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='highest_exp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lose_streak',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lowest_exp',
        ),
        migrations.RemoveField(
            model_name='player',
            name='offence',
        ),
        migrations.RemoveField(
            model_name='player',
            name='played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='win_streak',
        ),
        migrations.DeleteModel(
            name='ExpHistoryLegacy',
        ),
        migrations.DeleteModel(
            name='MatchLegacy',
        ),
    ]
