# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0020_auto_20170224_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='defence',
            new_name='defence_won',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='offence',
            new_name='offence_won',
        ),
    ]
