# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0021_auto_20170330_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='defence_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='offence_played',
            field=models.IntegerField(default=0),
        ),
    ]
