# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0022_auto_20170330_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='played',
        ),
    ]
