# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0023_remove_member_played'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('team', 'username')]),
        ),
    ]
