# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0026_auto_20170422_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='exphistory',
            name='matches_played',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exphistory',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='exphistory',
            unique_together=set([('player', 'date')]),
        ),
    ]
