# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0027_auto_20170423_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
