# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-28 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0028_auto_20170423_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activation_code',
            field=models.CharField(default='', max_length=28),
        ),
    ]
