# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-08 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0030_auto_20170628_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='activation_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='playerplaceholder',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholder', to='tfoosball.Member'),
        ),
    ]
