# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0031_auto_20171008_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
        migrations.AlterField(
            model_name='member',
            name='activation_code',
            field=models.CharField(blank=True, default='', max_length=384),
        ),
    ]
