# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0032_auto_20171102_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='whats_new_version',
            field=models.IntegerField(default=0),
        ),
    ]
