# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0034_whatsnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
