# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0035_member_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_default',
        ),
        migrations.AddField(
            model_name='player',
            name='default_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_team', to='tfoosball.Team'),
        ),
    ]
