# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0036_auto_20180107_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='invitation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
