# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0037_auto_20180113_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
