# Generated by Django 2.1 on 2018-08-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0038_auto_20180208_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
