# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('red_score', models.IntegerField()),
                ('blue_score', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='win_ratio',
            field=models.FloatField(db_column='win', default=0.0),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_att',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_att', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='blue_def',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_def', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='red_att',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_att', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='red_def',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_def', to=settings.AUTH_USER_MODEL),
        ),
    ]
