# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0005_exphistory'),
        ('tfoosball', '0006_auto_20161023_1351'),
    ]

    operations = [
    ]
