# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfoosball', '0007_merge_20161023_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exphistory',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
